import sys

Import('env')

liblwip_env = env.Clone()

src = [
    "src/arch/sys_arch.c",
    "src/arch/etherif.c",
    "src/api/api_lib.c",
    "src/api/api_msg.c",
    "src/api/err.c",
    "src/api/netbuf.c",
    "src/api/netdb.c",
    "src/api/netifapi.c",
    "src/api/sockets.c",
    "src/api/tcpip.c",
    "src/core/def.c",
    "src/core/dhcp.c",
    "src/core/dns.c",
    "src/core/init.c",
    "src/core/ipv4/autoip.c",
    "src/core/ipv4/icmp.c",
    "src/core/ipv4/igmp.c",
    "src/core/ipv4/inet.c",
    "src/core/ipv4/inet_chksum.c",
    "src/core/ipv4/ip.c",
    "src/core/ipv4/ip_addr.c",
    "src/core/ipv4/ip_frag.c",
    "src/core/mem.c",
    "src/core/memp.c",
    "src/core/netif.c",
    "src/core/pbuf.c",
    "src/core/raw.c",
    "src/core/stats.c",
    "src/core/sys.c",
    "src/core/tcp.c",
    "src/core/tcp_in.c",
    "src/core/tcp_out.c",
    "src/core/timers.c",
    "src/core/udp.c",
    "src/netif/etharp.c",
]

liblwip_env.Append(CPPFLAGS = ['-nostdinc'])
liblwip_env.Append(CPPPATH = ['#build/include', '#build/include/ipv4'])

liblwip_env.StaticLibrary("liblwip", src)

